import {  MenuProps } from "./interfaces/MenuProps";

export const data: MenuProps[] = [
  {
    id: 1,
    title: "Enchiladas",
    category: "mexican food",
    price: 20.6,
    img: "https://images.pexels.com/photos/9772454/pexels-photo-9772454.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "With rice, Jack cheese, black beans, salsa, and filling of your choice. Rolled in a flour tortilla and topped with salsas melted Jack cheese, sour cream, guacamole, and GYG's corn chips.",
  },
  {
    id: 2,
    title: "Mozzarella Sticks (7pcs)",
    category: "fast food",
    price: 15,
    img: "https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "Served with homemade tomato dip",
  },
  {
    id: 3,
    title: "Crepe Breakfast",
    category: "breakfast",
    price: 22,
    img: "https://images.pexels.com/photos/3225499/pexels-photo-3225499.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "One egg, ham, mushrooms, caramelised onions, mozzarella and spring onions. Served with salad and tomato relish on side.",
  },
  {
    id: 4,
    title: "Churros & Dulce de Leche",
    category: "mexican food",
    price: 5,
    img: "https://images.pexels.com/photos/372851/pexels-photo-372851.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "Churros rolled in cinnamon sugar and served with GYG's Dulce de Leche 1530kJ.",
  },
  {
    id: 5,
    title: "Margherita",
    category: "fast food",
    price: 23,
    img: "https://images.pexels.com/photos/6605214/pexels-photo-6605214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "tomato base, fior di latte, oregano and basil (v)",
  },
  {
    id: 6,
    title: "Ferrero Rocher",
    category: "breakfast",
    price: 5,
    img: "https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "Milk Chocolate Mousse with Premium French couverture Chocolate, Praline Mousse with Hazelnut and Almond, Almond Biscuit at the base, Crunchy Biscuit crumb in the middle. (This product contains Gluten, Dairy, egg, nuts, milk)",
  },
  {
    id: 7,
    title: "Three Hard Tacos",
    category: "mexican food",
    price: 19.4,
    img: "https://images.pexels.com/photos/7613568/pexels-photo-7613568.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "Jack cheese, Iceberg lettuce, salsa and filling, in a Chipotle-seasoned hard shell corn tortilla.",
  },
  {
    id: 8,
    title: "Fettuccine Meatballs",
    category: "fast food",
    price: 29,
    img: "https://images.pexels.com/photos/1435896/pexels-photo-1435896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "fettuccine served with meatballs and bolognese sauce",
  },
  {
    id: 9,
    title: "Flat white",
    category: "breakfast",
    price: 5,
    img: "https://images.pexels.com/photos/5840409/pexels-photo-5840409.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    desc: "milk and cream",
  },
];
